# Generated by Django 3.2.9 on 2021-12-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('name', models.CharField(
                    max_length=50,
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='Actor name'
                )),
                ('age', models.IntegerField(
                    verbose_name='Age of the Actor'
                )),
                ('gender', models.CharField(
                    choices=[('m', 'male'), ('f', 'female')],
                    default='male',
                    max_length=6,
                    verbose_name='Actors gender'
                )),
            ],
        ),
    ]
