# Generated by Django 3.2.9 on 2021-12-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(
                    max_length=50,
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='Movie title'
                )),
                ('category', models.CharField(
                    max_length=20,
                    verbose_name='Movie category'
                )),
                ('cast', models.ManyToManyField(
                    related_name='movies',
                    to='actors.Actor',
                    verbose_name='Movie Actors'
                )),
            ],
        ),
    ]
